### ISSUE TITLE
Extended Euclidian Algorithm

### ISSUE THREAD

**Issue by plasmatic1** [crackersamdjam/Templates#7]
IMO for this function here in `math.cpp` it should be made more clear that this is the Extended Euclidian algorithm since it's not totally clear to someone who is inexperienced/first time looking at this repo.

```
int gcd(int a, int b, int &x, int &y) {
    if (a == 0) {
        x = 0;
        y = 1;
        return b;
    }
    int x1, y1;
    int d = gcd(b % a, a, x1, y1);
    x = y1 - (b / a) * x1;
    y = x1;
    return d;
}
```

**Comment by imasheepow** [comment]
nou

**Comment by crackersamdjam** [comment]
get good moses 🐒
